/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  account_list: () => import("@/views/account/list/index.vue"),
  aiplatform_cost: () => import("@/views/aiplatform/cost/index.vue"),
  aiplatform_material: () => import("@/views/aiplatform/material/index.vue"),
  aiplatform_order: () => import("@/views/aiplatform/order/index.vue"),
  aiplatform_price_entry: () => import("@/views/aiplatform/price_entry/index.vue"),
  aiplatform_project: () => import("@/views/aiplatform/project/index.vue"),
  aiplatform_workspace: () => import("@/views/aiplatform/workspace/index.vue"),
  app_list: () => import("@/views/app/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  payment_channel_log: () => import("@/views/payment/channel/log/index.vue"),
  payment_operation: () => import("@/views/payment/operation/index.vue"),
  payment_order: () => import("@/views/payment/order/index.vue"),
  payment_refund: () => import("@/views/payment/refund/index.vue"),
  payment_stats: () => import("@/views/payment/stats/index.vue"),
};
