/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'account',
    path: '/account',
    component: 'layout.base',
    meta: {
      title: 'account',
      i18nKey: 'route.account'
    },
    children: [
      {
        name: 'account_list',
        path: '/account/list',
        component: 'view.account_list',
        meta: {
          title: 'account_list',
          i18nKey: 'route.account_list'
        }
      }
    ]
  },
  {
    name: 'aiplatform',
    path: '/aiplatform',
    component: 'layout.base',
    meta: {
      title: 'aiplatform',
      i18nKey: 'route.aiplatform'
    },
    children: [
      {
        name: 'aiplatform_order',
        path: '/aiplatform/order',
        component: 'view.aiplatform_order',
        meta: {
          title: 'aiplatform_order',
          i18nKey: 'route.aiplatform_order'
        }
      },
      {
        name: 'aiplatform_project',
        path: '/aiplatform/project',
        component: 'view.aiplatform_project',
        meta: {
          title: 'aiplatform_project',
          i18nKey: 'route.aiplatform_project'
        }
      }
    ]
  },
  {
    name: 'app',
    path: '/app',
    component: 'layout.base',
    meta: {
      title: 'app',
      i18nKey: 'route.app'
    },
    children: [
      {
        name: 'app_list',
        path: '/app/list',
        component: 'view.app_list',
        meta: {
          title: 'app_list',
          i18nKey: 'route.app_list'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      }
    ]
  },
  {
    name: 'payment',
    path: '/payment',
    component: 'layout.base',
    meta: {
      title: 'payment',
      i18nKey: 'route.payment'
    },
    children: [
      {
        name: 'payment_channel',
        path: '/payment/channel',
        meta: {
          title: 'payment_channel',
          i18nKey: 'route.payment_channel'
        },
        children: [
          {
            name: 'payment_channel_log',
            path: '/payment/channel/log',
            component: 'view.payment_channel_log',
            meta: {
              title: 'payment_channel_log',
              i18nKey: 'route.payment_channel_log'
            }
          }
        ]
      },
      {
        name: 'payment_operation',
        path: '/payment/operation',
        component: 'view.payment_operation',
        meta: {
          title: 'payment_operation',
          i18nKey: 'route.payment_operation'
        }
      },
      {
        name: 'payment_order',
        path: '/payment/order',
        component: 'view.payment_order',
        meta: {
          title: 'payment_order',
          i18nKey: 'route.payment_order'
        }
      },
      {
        name: 'payment_refund',
        path: '/payment/refund',
        component: 'view.payment_refund',
        meta: {
          title: 'payment_refund',
          i18nKey: 'route.payment_refund'
        }
      },
      {
        name: 'payment_stats',
        path: '/payment/stats',
        component: 'view.payment_stats',
        meta: {
          title: 'payment_stats',
          i18nKey: 'route.payment_stats'
        }
      }
    ]
  }
];
